name: Deploy to Vercel (dashboard-ativuz)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Production
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_HnDEwhCVw7YpAYN518hc2BtY
          VERCEL_PROJECT_ID: prj_r0phoaLEQvl2RSyaMI9jmAUSFP3w
